language: elixir
elixir:
- 1.4
env:
  - TRAVIS_NODE_VERSION="8"
sudo: false
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz"
  - "mkdir geckodriver"
  - "tar -xzf geckodriver-v0.17.0-linux64.tar.gz -C geckodriver"
  - "export PATH=$PATH:$PWD/geckodriver"
  - "bash test/travis/start_selenium.sh"
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - "mix local.hex --force"
  - mix local.rebar --force
install:
  - "mix deps.get"
  - "yarn"
  - "(cd example_dashboard && mix deps.get)"
  - "(cd example_dashboard && yarn)"
  - "(cd example_dashboard && brunch b)"
  - "(cd installer && mix deps.get)"
script: "./pre-commit.sh"
cache:
  yarn: true
addons:
    firefox: "54.0"
    apt:
      packages:
        - oracle-java8-set-default
